commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("randompage", views.randompage, name="randompage"),
    path("create", views.create, name="create"),
    path("update", views.update, name="update"),
    path("wiki/<str:name>", views.wiki, name="wiki"),
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms 

class CreateWiki(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea, label="Content")

class UpdateWiki(forms.Form):
    title = forms.CharField(widget=forms.HiddenInput())
    content = forms.CharField(widget=forms.Textarea(attrs=None))

encyclopedia/views.py
from django.contrib import messages
from django.http import HttpResponseNotFound, Http404, JsonResponse
from django.shortcuts import HttpResponse, redirect, render
from django.template.loader import render_to_string
from markdown2 import Markdown
import random

from . import util, forms


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def wiki(request, name):
    entry = util.get_entry(name)
    
    if entry:
        # https://github.com/trentm/python-markdown2
        entry = Markdown().convert(entry)
        return render(request, 'encyclopedia/wiki.html', {
            "entry": entry,
            "title": name
        })
    else:
        # https://docs.djangoproject.com/en/5.0/topics/http/views/#customizing-error-views
        raise Http404(f"A Wiki for {name} does not exist")
        

def search(request):
    if request.method == 'POST':
        search = request.POST
        title = search['q'].lower()

        entries = util.list_entries()
        
        lowercase_entries = []
        for entry in entries:
            lowercase_entries.append(entry.lower())

        if title in lowercase_entries:
            return redirect(f'wiki/{title}')

        else:
            search_entry = []     
            for entry in entries:
                if search['q'].lower() in entry.lower():
                    search_entry.append(entry)

            return render(request, 'encyclopedia/search.html', {
                'search_entry': search_entry
            })
    else:
        return HttpResponse('hi')

    # Responsive search bar 
    # if request.method == "GET":
    #     search = request.GET.get('data')
    #     entries = util.list_entries()
        
    #     search_entry = []

    #     # https://www.askpython.com/python/list/find-string-in-list-python
    #     for entry in entries:
    #         if search.lower() in entry.lower():
    #             search_entry.append(entry)

    #     # https://stackoverflow.com/questions/70652414/how-to-render-django-template-after-ajax-call
    #     html = render_to_string('encyclopedia/search.html', {
    #         'search_entry': search_entry
    #     })
    #     print(html)

    #     return JsonResponse({'data': html}, safe=False)
    # else:
    #     data = request.POST
    #     title = data['q']
    #     return redirect(f'wiki/{title}')
            

def create(request):
    # https://docs.djangoproject.com/en/5.0/topics/forms/
    if request.method == "GET":
        form = forms.CreateWiki()

        return render(request, "encyclopedia/create.html", {
            "form": form
        })

    else:
        form = forms.CreateWiki(request.POST)

        if form.is_valid():
            entry = form.cleaned_data
            title = entry["title"].capitalize()
            content = entry["content"]

            entries = util.list_entries()
        
            lowercase_entries = []
            for entry in entries:
                lowercase_entries.append(entry.lower())
            
            if title.lower() in lowercase_entries:
                # https://docs.djangoproject.com/en/5.0/ref/contrib/messages/
                messages.error(request, "The Wiki entry you tried to create already exists.")
                return redirect('/create')
            else:
                util.save_entry(title, content)

            return redirect(f'wiki/{title}')


def randompage(request):
    entries = util.list_entries()

    random_entry = random.choice(entries)

    return redirect(f'wiki/{random_entry}')

def update(request):
    if request.method == "GET":
        data = request.GET

        title = data['title']

        # Retreive entry given the title 
        entry = util.get_entry(title)

        form = forms.UpdateWiki()

        # https://stackoverflow.com/questions/813418/django-set-field-value-after-a-form-is-initialized
        form.fields['title'].initial = title
        form.fields['content'].initial = entry
        
        return render(request, 'encyclopedia/update.html', {
            "form": form,
            "title": title
        })

    else:
        data = request.POST
        
        content = data['content']
        title = data['title']

        util.save_entry(title, content)

        return redirect(f'wiki/{title}')

encyclopedia/templates/encyclopedia/create.html
{%  extends "encyclopedia/layout.html" %}

{% block title %}
    
{% endblock %}

{% block body %}
    <h1>Create a new Wiki entry</h1>
    {% if messages %}
        {% for message in messages %}
            <h6 style="color: red;">{{ message }}</h6>
        {% endfor %}
    {% endif %}
    <div class="create_form_container">
        <form id="id_create_form" action="{% url 'encyclopedia:create' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary" id="id_submit_create_form" type="submit">
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' name=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}


<!-- https://stackoverflow.com/questions/25345392/how-to-add-url-parameters-to-django-template-url-tag -->

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form id="search_form" method="post" action="{% url 'encyclopedia:search' %}">
                    {% csrf_token %}
                    <input autocomplete="off" id="inputSearch" class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <div class="" id="searchList"></div>
                </form>
                
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{%  url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
    
    <script>
        
        // document.addEventListener('DOMContentLoaded', () => {
        //     document.querySelector('#inputSearch').addEventListener('keyup', function(event) {
        //         search = document.querySelector('#inputSearch').value.toLowerCase()
        //         // console.log(search)
        //         $.ajax({
        //             url: "{% url 'encyclopedia:search' %}",
        //             data: {'data': search},
        //             type: 'GET',
        //             success: function(response) {
        //                 //console.log(response.data)
        //                 document.querySelector('#searchList').innerHTML = response.data
        //                 if (search === "") {
        //                     document.querySelector('#searchList').innerHTML = ""
        //                 }
        //             },
        //             error: function(error) {
        //                 console.log(error);
        //             }
        //         });
        //     })
        // })
    </script>

</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}


{% block title %}

{% endblock %}

{% block body %}
    <h1>Search Results:</h1>
    {% for entry in search_entry %}

    <a href="{% url 'encyclopedia:wiki' name=entry %}">{{ entry }}</a>
    <br>

    {% endfor %}
{% endblock %}

encyclopedia/templates/encyclopedia/update.html
{%  extends "encyclopedia/layout.html" %}

{% block title %}
    
{% endblock %}

{% block body %}
    <h1>Update {{ title }} Wiki</h1>
    <div class="create_form_container">
        <form id="id_create_form" action="{% url 'encyclopedia:update' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary" id="id_submit_create_form" type="submit">
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{%  extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }} Wiki
{% endblock %}

{% block body %}
    {{ entry|safe }}
    <form action="{% url 'encyclopedia:update' %}" method="GET">
        <input type="hidden" name="title" value="{{title}}" id="">
        <button class="btn btn-primary" type="submit">Edit Wiki</button>
    </form>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
{% endblock %}